package game.event;

public enum EventType {
    PLAYER_JOINED,
    WHITE_CARD_NEW,
    WHITE_CARD_PLAYED,
    WHITE_CARD_WINNER,
    BLACK_CARD_NEW,
    CARD_TZAR_CHOSEN,
    ROUND_PLAYER_CHOSEN,
    GAME_STARTED,
    WHITE_CARD_REQUEST, WINNER_CARD_REQUEST, REQUESTING_CHOICE,
    WHITE_CARD_CHOSEN,
    REFRESH_STATE
}
